# Generated by Django 5.1.1 on 2024-10-01 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmz', '0002_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='model',
            new_name='car_model',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='kilometers_driven',
            new_name='kilo_driven',
        ),
    ]
